"use client";
import {useEffect,useState} from "react";
const API=process.env.NEXT_PUBLIC_API_URL||(process.env.NODE_ENV==="production"?"":"http://localhost:8000");
type Run={id:string;company:string;fiscal_period:string;status:string};
type Ev={citation:{source_id:string;locator:string;supporting_excerpt:string}};
type Turn={sequence:number;round:number;role:string;turn_type:string;argument:string;evidence:Ev[];confidence:number};
type Debate={id:string;topic:string;company:string;status:string;progress:number;transcript:Turn[];verdict:null|{decision:string;conviction:number;synthesis:string;strongest_bull_case:string;strongest_bear_case:string;key_uncertainties:string[];monitoring_triggers:string[];rubric:{dimension:string;score:number;rationale:string}[];disclaimer:string};events:{sequence:number;kind:string;message:string}[]};
export default function DebatePage(){const[runs,setRuns]=useState<Run[]>([]),[items,setItems]=useState<Debate[]>([]),[selected,setSelected]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");const current=items.find(x=>x.id===selected);
 async function load(){const[a,b]=await Promise.all([fetch(`${API}/api/v1/research-runs`).then(r=>r.json()),fetch(`${API}/api/v1/research-debates`).then(r=>r.json())]);setRuns(a.filter((x:Run)=>x.status==="completed"));setItems(b);if(!selected&&b[0])setSelected(b[0].id)}useEffect(()=>{load()},[]);useEffect(()=>{if(!current||current.status!=="running")return;const t=setInterval(load,600);return()=>clearInterval(t)},[current?.status,current?.id]);
 async function create(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget),r=await fetch(`${API}/api/v1/research-debates`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({topic:f.get("topic"),source_run_id:f.get("source_run_id"),language:f.get("language"),rebuttal_rounds:Number(f.get("rounds"))})});if(r.ok){const d=await r.json();setSelected(d.id);await load()}else{setError((await r.json()).detail)}setBusy(false)}
 return <main><header><div className="brand">SIGNAL<span>FORGE</span></div><div className="badge">POC 04 · RESEARCH DEBATE</div></header><section className="debate-hero"><div><p className="eyebrow">AGENT-AS-TOOL · ADVERSARIAL RESEARCH</p><h1>讓多空交鋒，<em>由證據裁決。</em></h1><p className="lede">Bull、Bear 與 PM 逐輪挑戰論點，Critic 最後檢查引用與決策品質。</p></div><form className="debate-launcher" onSubmit={create}><label>研究問題<input name="topic" defaultValue="目前法說證據是否支持 AI 成長論點？" required/></label><label>證據來源<select name="source_run_id">{runs.map(r=><option key={r.id} value={r.id}>{r.company.toUpperCase()} · {r.fiscal_period}</option>)}</select></label><label>語言<select name="language"><option value="zh-TW">繁體中文</option><option value="en">English</option></select></label><label>反駁回合<select name="rounds"><option value="1">1 round</option><option value="2">2 rounds</option><option value="3">3 rounds</option></select></label><button disabled={busy||!runs.length}>{busy?"辯論中…":"啟動辯論 →"}</button>{error&&<p className="debate-error">{error}</p>}</form></section><section className="debate-select"><b>DEBATE</b><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">尚無辯論</option>{items.map(x=><option key={x.id} value={x.id}>{x.company.toUpperCase()} · {x.topic} · {x.status}</option>)}</select>{current&&<><span>{current.status.toUpperCase()}</span><b>{current.progress}%</b></>}</section>
 {current?<section className="arena"><article className="transcript"><p className="eyebrow">DEBATE TRANSCRIPT</p><h2>{current.topic}</h2>{current.transcript.map(t=><div className="turn" key={t.sequence}><div className={`role ${t.role}`}>{t.role.toUpperCase()}<br/>R{t.round}</div><div><h3>{t.turn_type} · {t.confidence}%</h3><p>{t.argument}</p>{t.evidence.slice(0,2).map((x,i)=><blockquote key={i}><code>{x.citation.source_id}:{x.citation.locator}</code><br/>{x.citation.supporting_excerpt}</blockquote>)}</div></div>)}{current.verdict&&<div className="verdict"><div className="verdict-head"><div><p className="eyebrow">PM VERDICT</p><h2>{current.verdict.decision.toUpperCase()}</h2></div><strong>{current.verdict.conviction}%</strong></div><p>{current.verdict.synthesis}</p><h3>Key uncertainties</h3>{current.verdict.key_uncertainties.map(x=><p key={x}>— {x}</p>)}<h3>Monitoring triggers</h3>{current.verdict.monitoring_triggers.map(x=><p key={x}>+ {x}</p>)}<p className="disclaimer">{current.verdict.disclaimer}</p></div>}</article><aside className="debate-side"><div className="panel"><p className="eyebrow">CRITIC RUBRIC</p>{current.verdict?.rubric.map(x=><div className="rubric" key={x.dimension}><span>{x.dimension}</span><b>{x.score}</b></div>)||<p>Awaiting verdict…</p>}</div><div className="panel"><p className="eyebrow">TRAJECTORY</p>{current.events.map(x=><div className="event" key={x.sequence}><i/><div><b>{x.kind}</b><span>{x.message}</span></div></div>)}</div></aside></section>:<section className="debate-empty"><h2>選擇一份已完成的 Earnings Run，建立第一場研究辯論。</h2></section>}</main>}
