"use client";

import {useEffect, useMemo, useState} from "react";
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000";
type Task={id:string;agent_role:string;objective:string;status:string};
type Investigation={id:string;subject:string;status:string;current_step:string|null;progress:number;tasks:Task[];error:string|null};
type Evidence={citation:{source_id:string;locator:string;supporting_excerpt:string};source_date:string;primary_source:boolean};
type Node={id:string;type:string;name:string;ticker?:string};
type Edge={id:string;source_entity_id:string;target_entity_id:string;type:string;confidence:number;inference_level:string;evidence:Evidence[]};
type Graph={version:string;nodes:Node[];edges:Edge[];conflicts:{id:string;description:string;status:string}[]};
type Candidate={company_entity_id:string;exposure:string;benefit_mechanism:string;evidence_path:string[];risks:string[];confidence:number;primary_source_count:number};
type Report={summary:string;candidates:Candidate[];disclaimer:string};
type Trace={agents:{agent_role:string;status:string;tool_calls:number;duration_ms:number}[];tool_calls:number;duration_ms:number;estimated_cost_usd:number};
const positions:Record<string,[number,number]>={nvidia:[13,18],"ai-accelerators":[35,24],cowos:[58,13],tsmc:[82,20],hbm:[58,43],"sk-hynix":[83,48],"data-center-power-cooling":[48,75],vertiv:[77,81]};

export default function SupplyChainPage(){
 const [items,setItems]=useState<Investigation[]>([]),[selected,setSelected]=useState(""),[graph,setGraph]=useState<Graph|null>(null),[report,setReport]=useState<Report|null>(null),[trace,setTrace]=useState<Trace|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[filter,setFilter]=useState("all"),[evidence,setEvidence]=useState<Edge|null>(null);
 const current=items.find(x=>x.id===selected);
 async function load(){const r=await fetch(`${API}/api/v1/supply-chain-investigations`),data=await r.json();setItems(data);if(!selected&&data[0])setSelected(data[0].id)}
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(!selected)return;const item=items.find(x=>x.id===selected);if(item?.status==="completed")Promise.all([fetch(`${API}/api/v1/supply-chain-investigations/${selected}/graph`).then(r=>r.json()),fetch(`${API}/api/v1/supply-chain-investigations/${selected}/report`).then(r=>r.json()),fetch(`${API}/api/v1/supply-chain-investigations/${selected}/trace`).then(r=>r.json())]).then(([g,r,t])=>{setGraph(g);setReport(r);setTrace(t)})},[selected,items]);
 useEffect(()=>{if(!current||!["queued","running"].includes(current.status))return;const timer=setInterval(load,700);return()=>clearInterval(timer)},[current?.status,current?.id]);
 async function create(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const f=new FormData(event.currentTarget),response=await fetch(`${API}/api/v1/supply-chain-investigations`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({signal_type:f.get("signal_type"),subject:f.get("subject"),time_window:f.get("time_window"),question:f.get("question"),language:f.get("language"),config:{max_tool_calls:Number(f.get("max_tool_calls")),max_cost_usd:Number(f.get("max_cost_usd"))}})});if(response.ok){const value=await response.json();setSelected(value.id);await load()}else{const body=await response.json();setError(body.detail||"Unable to start investigation")}setBusy(false)}
 async function action(name:"cancel"|"retry"){if(!current)return;await fetch(`${API}/api/v1/supply-chain-investigations/${current.id}/${name}`,{method:"POST"});await load()}
 const visible=useMemo(()=>graph?.nodes.filter(n=>filter==="all"||n.type===filter)||[],[graph,filter]),ids=new Set(visible.map(n=>n.id));
 return <main className="sc-app"><header><div className="brand">SIGNAL<span>FORGE</span></div><div className="badge">POC 03 · SUPPLY CHAIN DETECTIVE</div></header>
 <section className="sc-hero"><div className="sc-intro"><p className="eyebrow">MULTI-AGENT EVIDENCE GRAPH</p><h1>從瓶頸訊號，<em>追出受惠路徑。</em></h1><p className="lede">讓專職 agents 同步追查需求、產能與供應關係，再由 critic 檢查每一步推論。</p></div><form className="sc-form" onSubmit={create}><label>訊號<select name="signal_type"><option value="capacity_bottleneck">產能瓶頸</option><option value="shortage">缺貨</option><option value="price_increase">漲價</option></select></label><label>輸出語言<select name="language"><option value="zh-TW">繁體中文</option><option value="en">English</option></select></label><label className="wide">產品／技術<input name="subject" defaultValue="AI accelerators / CoWoS / HBM" required/></label><label>研究期間<input name="time_window" defaultValue="2024-Q4 to 2025-Q2" required/></label><label>工具上限<input name="max_tool_calls" type="number" defaultValue="30" min="1" max="100"/></label><label>成本上限 USD<input name="max_cost_usd" type="number" step=".1" defaultValue="2" min=".1"/></label><label className="wide">補充問題<textarea name="question" defaultValue="哪些上市公司具有可由一手來源支持的受惠路徑？"/></label><button disabled={busy}>{busy?"建立中…":"開始多 Agent 調查 →"}</button>{error&&<div className="sc-error">{error}</div>}</form></section>
 <section className="sc-strip"><b>INVESTIGATION</b><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">尚無調查</option>{items.map(x=><option key={x.id} value={x.id}>{x.subject} · {x.status}</option>)}</select>{current&&<><span>{current.status.toUpperCase()} · {current.current_step||"done"}</span><div className="sc-progress"><i style={{width:`${current.progress}%`}}/></div><b>{current.progress}%</b><div className="sc-actions">{["queued","running"].includes(current.status)&&<button onClick={()=>action("cancel")}>CANCEL</button>}{["cancelled","failed","awaiting_retry"].includes(current.status)&&<button onClick={()=>action("retry")}>RETRY</button>}</div></>}</section>
 {current?<section className="sc-body"><article className="sc-main"><p className="eyebrow">AGENT TASK GRAPH</p><div className="agent-lane">{current.tasks.map(t=><div key={t.id} className={`agent-card ${t.status}`}><b>{t.agent_role.toUpperCase()}</b><span>{t.status}</span></div>)}</div>{current.error&&<p className="sc-error">{current.error}</p>}
 {graph&&<><div className="graph-tools"><p className="eyebrow">EVIDENCE GRAPH · v{graph.version}</p><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All nodes</option><option value="company">Companies</option><option value="product">Products</option><option value="technology">Technology</option></select></div><div className="evidence-graph">{graph.edges.filter(e=>ids.has(e.source_entity_id)&&ids.has(e.target_entity_id)).map(e=>{const a=positions[e.source_entity_id]||[10,10],b=positions[e.target_entity_id]||[80,80],dx=b[0]-a[0],dy=b[1]-a[1],length=Math.sqrt(dx*dx+dy*dy);return <button title={`${e.type} · ${e.confidence}%`} onClick={()=>setEvidence(e)} key={e.id} className={`graph-edge ${e.inference_level}`} style={{left:`${a[0]}%`,top:`${a[1]}%`,width:`${length}%`,transform:`rotate(${Math.atan2(dy,dx)*180/Math.PI}deg)`,border:0,padding:0}}/>})}{visible.map(n=>{const p=positions[n.id]||[50,50];return <button key={n.id} className={`graph-node ${n.type}`} style={{left:`${p[0]}%`,top:`${p[1]}%`}} onClick={()=>setEvidence(graph.edges.find(e=>e.source_entity_id===n.id||e.target_entity_id===n.id)||null)}>{n.name}<small>{n.ticker||n.type}</small></button>})}</div></>}
 {report&&<><p className="eyebrow">EVIDENCE-QUALIFIED CANDIDATES</p><p className="summary">{report.summary}</p>{report.candidates.map(c=><div className="candidate" key={c.company_entity_id}><strong>{c.company_entity_id.toUpperCase()}</strong><div><h3>{c.exposure}</h3><p>{c.benefit_mechanism}</p><small>{c.primary_source_count} primary sources · {c.evidence_path.join(" → ")}</small><p><b>Risks:</b> {c.risks.join(" · ")}</p></div><div><b>{c.confidence}%</b><meter min="0" max="100" value={c.confidence}/><button className="path-button" onClick={()=>setEvidence(graph?.edges.find(e=>e.id===c.evidence_path[c.evidence_path.length-1])||null)}>VIEW PATH</button></div></div>)}<p className="disclaimer">{report.disclaimer}</p></>}
 </article><aside className="sc-aside"><div className="panel"><p className="eyebrow">CONTRADICTION CRITIC</p>{graph?.conflicts.map(c=><div className="conflict" key={c.id}><b>{c.status.toUpperCase()}</b><p>{c.description}</p></div>)||<p>Waiting for graph…</p>}</div><div className="panel"><p className="eyebrow">AGENT TRACE</p>{trace?.agents.map(a=><div className="trace-agent" key={a.agent_role}><span>{a.agent_role}</span><b>{a.status} · {a.tool_calls} tools</b></div>)}</div><div className="panel"><p className="eyebrow">RUN METADATA</p><div className="stat"><b>{trace?.tool_calls||0}</b><span>TOOL CALLS</span></div><div className="stat"><b>{trace?.duration_ms||0} ms</b><span>DURATION</span></div><div className="stat"><b>${(trace?.estimated_cost_usd||0).toFixed(4)}</b><span>ESTIMATED COST</span></div></div></aside></section>:<section className="sc-empty"><p className="eyebrow">NO INVESTIGATION YET</p><h2>建立第一個 AI 晶片供應鏈偵查。</h2></section>}
 {evidence&&<div className="citation-pop" onClick={()=>setEvidence(null)}><div className="citation-sheet" onClick={e=>e.stopPropagation()}><button onClick={()=>setEvidence(null)}>×</button><p className="eyebrow">RELATIONSHIP EVIDENCE</p><h2>{evidence.source_entity_id} → {evidence.target_entity_id}</h2><p>{evidence.type} · {evidence.confidence}% · {evidence.inference_level}</p>{evidence.evidence.map((item,i)=><blockquote key={i}><code>{item.citation.source_id} · {item.citation.locator} · {new Date(item.source_date).toLocaleDateString()}</code><p>{item.citation.supporting_excerpt}</p></blockquote>)}</div></div>}
 </main>
}
